### PR TITLE
Remove gulp from being installed by default for new components

### LINKED ISSUE #40: Remove gulpfile.js + node packages
to promote the helper more, the gulpfile.js should be removed from the 'component-structure' file and the node dependencies removed.  This will speed up 'component new' massively.

They can then use all the component commands out of the box. If they need something more complicated, like skycons, they create a gulp file for that one project.

The added bonus is people will get use to using the component commands in the projects

### PR DESCRIPTION
**Pull request by peter-mouland**
fixes #40

Welcome to discuss if you disagree

### CODE REVIEW

**Comment by peter-mouland** [comment]
@behaghel @rosswarren 
do you guys agree with this? It would be good to get this in v1.1.0 as it could also be seen as a breaking change.

**upside**
it would speed up the initial setup of components.  promote the use of the helper via CLI. less code to test.

**downside**
if the helper has a breaking change, all your projects would have to update the component.config.js file.

**Comment by behaghel** [comment]
I have reviewed it and I like it. I think it lowers the barriers to entry significantly. I didn't even see the downside, can you elaborate on it? Should we start having a `component.config.js` *definition version* or even put in there the semantic version of the component-helper it works well with? That would work as a form of acknowledgment by the component, pointing out it has adjusted to the breaking changes of the new version.

You have a typo in the directory `examples` (currently reads `exmaples`).

**Comment by peter-mouland** [comment]
by the downside, i mean, with v1.1.0 proposal we have changed the format of what the helper expects to find within component.config.js. This means when people upgrade the helper but run `component serve` on a project built with v1.0.0, nothing will happen apart from errors.

ok, on the other branch i will work out how to notify if they have an out of date config file form.

**Comment by behaghel** [comment]
I think having to update your config is really minimal. It will take me 2 minutes for sky-tags. Now I hear you, either we describe clearly the needed transformation or better, we script it.



—

**Comment by peter-mouland** [comment]
cool.

I have started work on the config notifying method - but dont think what i have right now is good enough. or easy to understand!

https://github.com/peter-mouland/component-helper/commit/10e75a6996ec1ecdbb83217963848c5fe8472f32

i think this gulp refactor is ready to merge then and the config notifier is a separate issue

**Pull request merged**
